/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Gender } from './Gender';
import {
    GenderFromJSON,
    GenderFromJSONTyped,
    GenderToJSON,
    GenderToJSONTyped,
} from './Gender';
import type { UserType } from './UserType';
import {
    UserTypeFromJSON,
    UserTypeFromJSONTyped,
    UserTypeToJSON,
    UserTypeToJSONTyped,
} from './UserType';

/**
 * 
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    userId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    accessToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    refreshToken?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof AuthResponse
     */
    accessTokenExpiration?: Date;
    /**
     * 
     * @type {UserType}
     * @memberof AuthResponse
     */
    userType?: UserType;
    /**
     * 
     * @type {Gender}
     * @memberof AuthResponse
     */
    gender?: Gender;
    /**
     * 
     * @type {Date}
     * @memberof AuthResponse
     */
    birthDate?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof AuthResponse
     */
    cityId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResponse
     */
    cityName?: string | null;
}



/**
 * Check if a given object implements the AuthResponse interface.
 */
export function instanceOfAuthResponse(value: object): value is AuthResponse {
    return true;
}

export function AuthResponseFromJSON(json: any): AuthResponse {
    return AuthResponseFromJSONTyped(json, false);
}

export function AuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'email': json['email'] == null ? undefined : json['email'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'accessTokenExpiration': json['accessTokenExpiration'] == null ? undefined : (new Date(json['accessTokenExpiration'])),
        'userType': json['userType'] == null ? undefined : UserTypeFromJSON(json['userType']),
        'gender': json['gender'] == null ? undefined : GenderFromJSON(json['gender']),
        'birthDate': json['birthDate'] == null ? undefined : (new Date(json['birthDate'])),
        'cityId': json['cityId'] == null ? undefined : json['cityId'],
        'cityName': json['cityName'] == null ? undefined : json['cityName'],
    };
}

export function AuthResponseToJSON(json: any): AuthResponse {
    return AuthResponseToJSONTyped(json, false);
}

export function AuthResponseToJSONTyped(value?: AuthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'email': value['email'],
        'userName': value['userName'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'accessTokenExpiration': value['accessTokenExpiration'] == null ? undefined : ((value['accessTokenExpiration']).toISOString()),
        'userType': UserTypeToJSON(value['userType']),
        'gender': GenderToJSON(value['gender']),
        'birthDate': value['birthDate'] === null ? null : ((value['birthDate'] as any)?.toISOString().substring(0,10)),
        'cityId': value['cityId'],
        'cityName': value['cityName'],
    };
}

