/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvailabilityResult
 */
export interface AvailabilityResult {
    /**
     * 
     * @type {boolean}
     * @memberof AvailabilityResult
     */
    taken?: boolean;
}

/**
 * Check if a given object implements the AvailabilityResult interface.
 */
export function instanceOfAvailabilityResult(value: object): value is AvailabilityResult {
    return true;
}

export function AvailabilityResultFromJSON(json: any): AvailabilityResult {
    return AvailabilityResultFromJSONTyped(json, false);
}

export function AvailabilityResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvailabilityResult {
    if (json == null) {
        return json;
    }
    return {
        
        'taken': json['taken'] == null ? undefined : json['taken'],
    };
}

export function AvailabilityResultToJSON(json: any): AvailabilityResult {
    return AvailabilityResultToJSONTyped(json, false);
}

export function AvailabilityResultToJSONTyped(value?: AvailabilityResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'taken': value['taken'],
    };
}

