/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeEmailResult
 */
export interface ChangeEmailResult {
    /**
     * 
     * @type {boolean}
     * @memberof ChangeEmailResult
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ChangeEmailResult
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChangeEmailResult
     */
    requiresConfirmation?: boolean;
}

/**
 * Check if a given object implements the ChangeEmailResult interface.
 */
export function instanceOfChangeEmailResult(value: object): value is ChangeEmailResult {
    return true;
}

export function ChangeEmailResultFromJSON(json: any): ChangeEmailResult {
    return ChangeEmailResultFromJSONTyped(json, false);
}

export function ChangeEmailResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeEmailResult {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'requiresConfirmation': json['requiresConfirmation'] == null ? undefined : json['requiresConfirmation'],
    };
}

export function ChangeEmailResultToJSON(json: any): ChangeEmailResult {
    return ChangeEmailResultToJSONTyped(json, false);
}

export function ChangeEmailResultToJSONTyped(value?: ChangeEmailResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'errorMessage': value['errorMessage'],
        'requiresConfirmation': value['requiresConfirmation'],
    };
}

