/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthResponse } from './AuthResponse';
import {
    AuthResponseFromJSON,
    AuthResponseFromJSONTyped,
    AuthResponseToJSON,
    AuthResponseToJSONTyped,
} from './AuthResponse';

/**
 * 
 * @export
 * @interface LoginResult
 */
export interface LoginResult {
    /**
     * 
     * @type {boolean}
     * @memberof LoginResult
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoginResult
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {AuthResponse}
     * @memberof LoginResult
     */
    authResponse?: AuthResponse;
}

/**
 * Check if a given object implements the LoginResult interface.
 */
export function instanceOfLoginResult(value: object): value is LoginResult {
    return true;
}

export function LoginResultFromJSON(json: any): LoginResult {
    return LoginResultFromJSONTyped(json, false);
}

export function LoginResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResult {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'authResponse': json['authResponse'] == null ? undefined : AuthResponseFromJSON(json['authResponse']),
    };
}

export function LoginResultToJSON(json: any): LoginResult {
    return LoginResultToJSONTyped(json, false);
}

export function LoginResultToJSONTyped(value?: LoginResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'errorMessage': value['errorMessage'],
        'authResponse': AuthResponseToJSON(value['authResponse']),
    };
}

