/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OperationResult
 */
export interface OperationResult {
    /**
     * 
     * @type {boolean}
     * @memberof OperationResult
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OperationResult
     */
    errorMessage?: string | null;
}

/**
 * Check if a given object implements the OperationResult interface.
 */
export function instanceOfOperationResult(value: object): value is OperationResult {
    return true;
}

export function OperationResultFromJSON(json: any): OperationResult {
    return OperationResultFromJSONTyped(json, false);
}

export function OperationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperationResult {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
    };
}

export function OperationResultToJSON(json: any): OperationResult {
    return OperationResultToJSONTyped(json, false);
}

export function OperationResultToJSONTyped(value?: OperationResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'errorMessage': value['errorMessage'],
    };
}

