/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthResponse } from './AuthResponse';
import {
    AuthResponseFromJSON,
    AuthResponseFromJSONTyped,
    AuthResponseToJSON,
    AuthResponseToJSONTyped,
} from './AuthResponse';

/**
 * 
 * @export
 * @interface RegisterResult
 */
export interface RegisterResult {
    /**
     * 
     * @type {boolean}
     * @memberof RegisterResult
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegisterResult
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {AuthResponse}
     * @memberof RegisterResult
     */
    authResponse?: AuthResponse;
}

/**
 * Check if a given object implements the RegisterResult interface.
 */
export function instanceOfRegisterResult(value: object): value is RegisterResult {
    return true;
}

export function RegisterResultFromJSON(json: any): RegisterResult {
    return RegisterResultFromJSONTyped(json, false);
}

export function RegisterResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResult {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'authResponse': json['authResponse'] == null ? undefined : AuthResponseFromJSON(json['authResponse']),
    };
}

export function RegisterResultToJSON(json: any): RegisterResult {
    return RegisterResultToJSONTyped(json, false);
}

export function RegisterResultToJSONTyped(value?: RegisterResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'errorMessage': value['errorMessage'],
        'authResponse': AuthResponseToJSON(value['authResponse']),
    };
}

