/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInformationDTO
 */
export interface UserInformationDTO {
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    lastName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    phone?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserInformationDTO
     */
    isEmailConfirmed?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserInformationDTO
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof UserInformationDTO
     */
    cityId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserInformationDTO
     */
    cityName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserInformationDTO
     */
    rating?: number;
}

/**
 * Check if a given object implements the UserInformationDTO interface.
 */
export function instanceOfUserInformationDTO(value: object): value is UserInformationDTO {
    return true;
}

export function UserInformationDTOFromJSON(json: any): UserInformationDTO {
    return UserInformationDTOFromJSONTyped(json, false);
}

export function UserInformationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInformationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'isEmailConfirmed': json['isEmailConfirmed'] == null ? undefined : json['isEmailConfirmed'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'cityId': json['cityId'] == null ? undefined : json['cityId'],
        'cityName': json['cityName'] == null ? undefined : json['cityName'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function UserInformationDTOToJSON(json: any): UserInformationDTO {
    return UserInformationDTOToJSONTyped(json, false);
}

export function UserInformationDTOToJSONTyped(value?: UserInformationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'userName': value['userName'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'phone': value['phone'],
        'isEmailConfirmed': value['isEmailConfirmed'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'cityId': value['cityId'],
        'cityName': value['cityName'],
        'rating': value['rating'],
    };
}

