/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRatingDTO } from './UserRatingDTO';
import {
    UserRatingDTOFromJSON,
    UserRatingDTOFromJSONTyped,
    UserRatingDTOToJSON,
    UserRatingDTOToJSONTyped,
} from './UserRatingDTO';

/**
 * 
 * @export
 * @interface UsersLookupResult
 */
export interface UsersLookupResult {
    /**
     * 
     * @type {boolean}
     * @memberof UsersLookupResult
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UsersLookupResult
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {Array<UserRatingDTO>}
     * @memberof UsersLookupResult
     */
    users?: Array<UserRatingDTO> | null;
}

/**
 * Check if a given object implements the UsersLookupResult interface.
 */
export function instanceOfUsersLookupResult(value: object): value is UsersLookupResult {
    return true;
}

export function UsersLookupResultFromJSON(json: any): UsersLookupResult {
    return UsersLookupResultFromJSONTyped(json, false);
}

export function UsersLookupResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersLookupResult {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserRatingDTOFromJSON)),
    };
}

export function UsersLookupResultToJSON(json: any): UsersLookupResult {
    return UsersLookupResultToJSONTyped(json, false);
}

export function UsersLookupResultToJSONTyped(value?: UsersLookupResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'errorMessage': value['errorMessage'],
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserRatingDTOToJSON)),
    };
}

