/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsersLookupRequest
 */
export interface UsersLookupRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof UsersLookupRequest
     */
    ids?: Array<string> | null;
}

/**
 * Check if a given object implements the UsersLookupRequest interface.
 */
export function instanceOfUsersLookupRequest(value: object): value is UsersLookupRequest {
    return true;
}

export function UsersLookupRequestFromJSON(json: any): UsersLookupRequest {
    return UsersLookupRequestFromJSONTyped(json, false);
}

export function UsersLookupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersLookupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
    };
}

export function UsersLookupRequestToJSON(json: any): UsersLookupRequest {
    return UsersLookupRequestToJSONTyped(json, false);
}

export function UsersLookupRequestToJSONTyped(value?: UsersLookupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
    };
}

