/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRatingDTO
 */
export interface UserRatingDTO {
    /**
     * 
     * @type {string}
     * @memberof UserRatingDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserRatingDTO
     */
    userName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UserRatingDTO
     */
    rating?: number;
}

/**
 * Check if a given object implements the UserRatingDTO interface.
 */
export function instanceOfUserRatingDTO(value: object): value is UserRatingDTO {
    return true;
}

export function UserRatingDTOFromJSON(json: any): UserRatingDTO {
    return UserRatingDTOFromJSONTyped(json, false);
}

export function UserRatingDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRatingDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'rating': json['rating'] == null ? undefined : json['rating'],
    };
}

export function UserRatingDTOToJSON(json: any): UserRatingDTO {
    return UserRatingDTOToJSONTyped(json, false);
}

export function UserRatingDTOToJSONTyped(value?: UserRatingDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userName': value['userName'],
        'rating': value['rating'],
    };
}

