/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcceptRequest
 */
export interface AcceptRequest {
    /**
     * 
     * @type {number}
     * @memberof AcceptRequest
     */
    listingId?: number;
}

/**
 * Check if a given object implements the AcceptRequest interface.
 */
export function instanceOfAcceptRequest(value: object): value is AcceptRequest {
    return true;
}

export function AcceptRequestFromJSON(json: any): AcceptRequest {
    return AcceptRequestFromJSONTyped(json, false);
}

export function AcceptRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'listingId': json['listingId'] == null ? undefined : json['listingId'],
    };
}

export function AcceptRequestToJSON(json: any): AcceptRequest {
    return AcceptRequestToJSONTyped(json, false);
}

export function AcceptRequestToJSONTyped(value?: AcceptRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listingId': value['listingId'],
    };
}

