/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApplicantInfo
 */
export interface ApplicantInfo {
    /**
     * 
     * @type {string}
     * @memberof ApplicantInfo
     */
    id?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ApplicantInfo
     */
    appliedAt?: Date;
}

/**
 * Check if a given object implements the ApplicantInfo interface.
 */
export function instanceOfApplicantInfo(value: object): value is ApplicantInfo {
    return true;
}

export function ApplicantInfoFromJSON(json: any): ApplicantInfo {
    return ApplicantInfoFromJSONTyped(json, false);
}

export function ApplicantInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicantInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'appliedAt': json['appliedAt'] == null ? undefined : (new Date(json['appliedAt'])),
    };
}

export function ApplicantInfoToJSON(json: any): ApplicantInfo {
    return ApplicantInfoToJSONTyped(json, false);
}

export function ApplicantInfoToJSONTyped(value?: ApplicantInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'appliedAt': value['appliedAt'] == null ? undefined : ((value['appliedAt']).toISOString()),
    };
}

