/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatStartRequest
 */
export interface ChatStartRequest {
    /**
     * 
     * @type {number}
     * @memberof ChatStartRequest
     */
    listingId?: number;
}

/**
 * Check if a given object implements the ChatStartRequest interface.
 */
export function instanceOfChatStartRequest(value: object): value is ChatStartRequest {
    return true;
}

export function ChatStartRequestFromJSON(json: any): ChatStartRequest {
    return ChatStartRequestFromJSONTyped(json, false);
}

export function ChatStartRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatStartRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'listingId': json['listingId'] == null ? undefined : json['listingId'],
    };
}

export function ChatStartRequestToJSON(json: any): ChatStartRequest {
    return ChatStartRequestToJSONTyped(json, false);
}

export function ChatStartRequestToJSONTyped(value?: ChatStartRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listingId': value['listingId'],
    };
}

