/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CitySearchResult
 */
export interface CitySearchResult {
    /**
     * 
     * @type {string}
     * @memberof CitySearchResult
     */
    externalId?: string;
    /**
     * 
     * @type {string}
     * @memberof CitySearchResult
     */
    name?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CitySearchResult
     */
    postalCodes?: Array<string> | null;
}

/**
 * Check if a given object implements the CitySearchResult interface.
 */
export function instanceOfCitySearchResult(value: object): value is CitySearchResult {
    return true;
}

export function CitySearchResultFromJSON(json: any): CitySearchResult {
    return CitySearchResultFromJSONTyped(json, false);
}

export function CitySearchResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CitySearchResult {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'name': json['name'] == null ? undefined : json['name'],
        'postalCodes': json['postalCodes'] == null ? undefined : json['postalCodes'],
    };
}

export function CitySearchResultToJSON(json: any): CitySearchResult {
    return CitySearchResultToJSONTyped(json, false);
}

export function CitySearchResultToJSONTyped(value?: CitySearchResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalId': value['externalId'],
        'name': value['name'],
        'postalCodes': value['postalCodes'],
    };
}

