/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecyclerMaterialBreakdown } from './RecyclerMaterialBreakdown';
import {
    RecyclerMaterialBreakdownFromJSON,
    RecyclerMaterialBreakdownFromJSONTyped,
    RecyclerMaterialBreakdownToJSON,
    RecyclerMaterialBreakdownToJSONTyped,
} from './RecyclerMaterialBreakdown';

/**
 * 
 * @export
 * @interface CityStatisticsResult
 */
export interface CityStatisticsResult {
    /**
     * 
     * @type {string}
     * @memberof CityStatisticsResult
     */
    cityName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CityStatisticsResult
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof CityStatisticsResult
     */
    totalApproximateWorth?: number;
    /**
     * 
     * @type {Array<RecyclerMaterialBreakdown>}
     * @memberof CityStatisticsResult
     */
    breakdown?: Array<RecyclerMaterialBreakdown> | null;
}

/**
 * Check if a given object implements the CityStatisticsResult interface.
 */
export function instanceOfCityStatisticsResult(value: object): value is CityStatisticsResult {
    return true;
}

export function CityStatisticsResultFromJSON(json: any): CityStatisticsResult {
    return CityStatisticsResultFromJSONTyped(json, false);
}

export function CityStatisticsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityStatisticsResult {
    if (json == null) {
        return json;
    }
    return {
        
        'cityName': json['cityName'] == null ? undefined : json['cityName'],
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'totalApproximateWorth': json['totalApproximateWorth'] == null ? undefined : json['totalApproximateWorth'],
        'breakdown': json['breakdown'] == null ? undefined : ((json['breakdown'] as Array<any>).map(RecyclerMaterialBreakdownFromJSON)),
    };
}

export function CityStatisticsResultToJSON(json: any): CityStatisticsResult {
    return CityStatisticsResultToJSONTyped(json, false);
}

export function CityStatisticsResultToJSONTyped(value?: CityStatisticsResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cityName': value['cityName'],
        'totalItems': value['totalItems'],
        'totalApproximateWorth': value['totalApproximateWorth'],
        'breakdown': value['breakdown'] == null ? undefined : ((value['breakdown'] as Array<any>).map(RecyclerMaterialBreakdownToJSON)),
    };
}

