/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateRecycleListingItemRequest } from './CreateRecycleListingItemRequest';
import {
    CreateRecycleListingItemRequestFromJSON,
    CreateRecycleListingItemRequestFromJSONTyped,
    CreateRecycleListingItemRequestToJSON,
    CreateRecycleListingItemRequestToJSONTyped,
} from './CreateRecycleListingItemRequest';

/**
 * 
 * @export
 * @interface CreateRecycleListingRequest
 */
export interface CreateRecycleListingRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingRequest
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingRequest
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingRequest
     */
    location?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateRecycleListingRequest
     */
    availableFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateRecycleListingRequest
     */
    availableTo?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingRequest
     */
    pickupTimeFrom?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingRequest
     */
    pickupTimeTo?: string | null;
    /**
     * 
     * @type {Array<CreateRecycleListingItemRequest>}
     * @memberof CreateRecycleListingRequest
     */
    items?: Array<CreateRecycleListingItemRequest> | null;
}

/**
 * Check if a given object implements the CreateRecycleListingRequest interface.
 */
export function instanceOfCreateRecycleListingRequest(value: object): value is CreateRecycleListingRequest {
    return true;
}

export function CreateRecycleListingRequestFromJSON(json: any): CreateRecycleListingRequest {
    return CreateRecycleListingRequestFromJSONTyped(json, false);
}

export function CreateRecycleListingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRecycleListingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'city': json['city'] == null ? undefined : json['city'],
        'location': json['location'] == null ? undefined : json['location'],
        'availableFrom': json['availableFrom'] == null ? undefined : (new Date(json['availableFrom'])),
        'availableTo': json['availableTo'] == null ? undefined : (new Date(json['availableTo'])),
        'pickupTimeFrom': json['pickupTimeFrom'] == null ? undefined : json['pickupTimeFrom'],
        'pickupTimeTo': json['pickupTimeTo'] == null ? undefined : json['pickupTimeTo'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CreateRecycleListingItemRequestFromJSON)),
    };
}

export function CreateRecycleListingRequestToJSON(json: any): CreateRecycleListingRequest {
    return CreateRecycleListingRequestToJSONTyped(json, false);
}

export function CreateRecycleListingRequestToJSONTyped(value?: CreateRecycleListingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'city': value['city'],
        'location': value['location'],
        'availableFrom': value['availableFrom'] == null ? undefined : ((value['availableFrom']).toISOString().substring(0,10)),
        'availableTo': value['availableTo'] == null ? undefined : ((value['availableTo']).toISOString().substring(0,10)),
        'pickupTimeFrom': value['pickupTimeFrom'],
        'pickupTimeTo': value['pickupTimeTo'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(CreateRecycleListingItemRequestToJSON)),
    };
}

