/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecycleMaterialType } from './RecycleMaterialType';
import {
    RecycleMaterialTypeFromJSON,
    RecycleMaterialTypeFromJSONTyped,
    RecycleMaterialTypeToJSON,
    RecycleMaterialTypeToJSONTyped,
} from './RecycleMaterialType';

/**
 * 
 * @export
 * @interface CreateRecycleListingItemRequest
 */
export interface CreateRecycleListingItemRequest {
    /**
     * 
     * @type {RecycleMaterialType}
     * @memberof CreateRecycleListingItemRequest
     */
    type?: RecycleMaterialType;
    /**
     * 
     * @type {number}
     * @memberof CreateRecycleListingItemRequest
     */
    quantity?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingItemRequest
     */
    depositClass?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateRecycleListingItemRequest
     */
    estimatedDepositPerUnit?: number | null;
}



/**
 * Check if a given object implements the CreateRecycleListingItemRequest interface.
 */
export function instanceOfCreateRecycleListingItemRequest(value: object): value is CreateRecycleListingItemRequest {
    return true;
}

export function CreateRecycleListingItemRequestFromJSON(json: any): CreateRecycleListingItemRequest {
    return CreateRecycleListingItemRequestFromJSONTyped(json, false);
}

export function CreateRecycleListingItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRecycleListingItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : RecycleMaterialTypeFromJSON(json['type']),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'depositClass': json['depositClass'] == null ? undefined : json['depositClass'],
        'estimatedDepositPerUnit': json['estimatedDepositPerUnit'] == null ? undefined : json['estimatedDepositPerUnit'],
    };
}

export function CreateRecycleListingItemRequestToJSON(json: any): CreateRecycleListingItemRequest {
    return CreateRecycleListingItemRequestToJSONTyped(json, false);
}

export function CreateRecycleListingItemRequestToJSONTyped(value?: CreateRecycleListingItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': RecycleMaterialTypeToJSON(value['type']),
        'quantity': value['quantity'],
        'depositClass': value['depositClass'],
        'estimatedDepositPerUnit': value['estimatedDepositPerUnit'],
    };
}

