/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRecycleListingRequest
 */
export interface CreateRecycleListingRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingRequest
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingRequest
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingRequest
     */
    location?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateRecycleListingRequest
     */
    estimatedValue?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecycleListingRequest
     */
    estimatedAmount?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateRecycleListingRequest
     */
    availableFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateRecycleListingRequest
     */
    availableTo?: Date;
}

/**
 * Check if a given object implements the CreateRecycleListingRequest interface.
 */
export function instanceOfCreateRecycleListingRequest(value: object): value is CreateRecycleListingRequest {
    return true;
}

export function CreateRecycleListingRequestFromJSON(json: any): CreateRecycleListingRequest {
    return CreateRecycleListingRequestFromJSONTyped(json, false);
}

export function CreateRecycleListingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRecycleListingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'city': json['city'] == null ? undefined : json['city'],
        'location': json['location'] == null ? undefined : json['location'],
        'estimatedValue': json['estimatedValue'] == null ? undefined : json['estimatedValue'],
        'estimatedAmount': json['estimatedAmount'] == null ? undefined : json['estimatedAmount'],
        'availableFrom': json['availableFrom'] == null ? undefined : (new Date(json['availableFrom'])),
        'availableTo': json['availableTo'] == null ? undefined : (new Date(json['availableTo'])),
    };
}

export function CreateRecycleListingRequestToJSON(json: any): CreateRecycleListingRequest {
    return CreateRecycleListingRequestToJSONTyped(json, false);
}

export function CreateRecycleListingRequestToJSONTyped(value?: CreateRecycleListingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'city': value['city'],
        'location': value['location'],
        'estimatedValue': value['estimatedValue'],
        'estimatedAmount': value['estimatedAmount'],
        'availableFrom': value['availableFrom'] == null ? undefined : ((value['availableFrom']).toISOString()),
        'availableTo': value['availableTo'] == null ? undefined : ((value['availableTo']).toISOString()),
    };
}

