/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DonorStatisticsResult
 */
export interface DonorStatisticsResult {
    /**
     * 
     * @type {number}
     * @memberof DonorStatisticsResult
     */
    listingCount?: number;
    /**
     * 
     * @type {number}
     * @memberof DonorStatisticsResult
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof DonorStatisticsResult
     */
    totalApproximateWorth?: number;
}

/**
 * Check if a given object implements the DonorStatisticsResult interface.
 */
export function instanceOfDonorStatisticsResult(value: object): value is DonorStatisticsResult {
    return true;
}

export function DonorStatisticsResultFromJSON(json: any): DonorStatisticsResult {
    return DonorStatisticsResultFromJSONTyped(json, false);
}

export function DonorStatisticsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DonorStatisticsResult {
    if (json == null) {
        return json;
    }
    return {
        
        'listingCount': json['listingCount'] == null ? undefined : json['listingCount'],
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'totalApproximateWorth': json['totalApproximateWorth'] == null ? undefined : json['totalApproximateWorth'],
    };
}

export function DonorStatisticsResultToJSON(json: any): DonorStatisticsResult {
    return DonorStatisticsResultToJSONTyped(json, false);
}

export function DonorStatisticsResultToJSONTyped(value?: DonorStatisticsResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listingCount': value['listingCount'],
        'totalItems': value['totalItems'],
        'totalApproximateWorth': value['totalApproximateWorth'],
    };
}

