/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ListingStatus = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4,
    NUMBER_5: 5,
    NUMBER_6: 6
} as const;
export type ListingStatus = typeof ListingStatus[keyof typeof ListingStatus];


export function instanceOfListingStatus(value: any): boolean {
    for (const key in ListingStatus) {
        if (Object.prototype.hasOwnProperty.call(ListingStatus, key)) {
            if (ListingStatus[key as keyof typeof ListingStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ListingStatusFromJSON(json: any): ListingStatus {
    return ListingStatusFromJSONTyped(json, false);
}

export function ListingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListingStatus {
    return json as ListingStatus;
}

export function ListingStatusToJSON(value?: ListingStatus | null): any {
    return value as any;
}

export function ListingStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ListingStatus {
    return value as ListingStatus;
}

