/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MarkReadRequest
 */
export interface MarkReadRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof MarkReadRequest
     */
    ids?: Array<number> | null;
}

/**
 * Check if a given object implements the MarkReadRequest interface.
 */
export function instanceOfMarkReadRequest(value: object): value is MarkReadRequest {
    return true;
}

export function MarkReadRequestFromJSON(json: any): MarkReadRequest {
    return MarkReadRequestFromJSONTyped(json, false);
}

export function MarkReadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MarkReadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'] == null ? undefined : json['ids'],
    };
}

export function MarkReadRequestToJSON(json: any): MarkReadRequest {
    return MarkReadRequestToJSONTyped(json, false);
}

export function MarkReadRequestToJSONTyped(value?: MarkReadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
    };
}

