/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeetingPointRequest
 */
export interface MeetingPointRequest {
    /**
     * 
     * @type {number}
     * @memberof MeetingPointRequest
     */
    listingId?: number;
    /**
     * 
     * @type {number}
     * @memberof MeetingPointRequest
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof MeetingPointRequest
     */
    longitude?: number;
}

/**
 * Check if a given object implements the MeetingPointRequest interface.
 */
export function instanceOfMeetingPointRequest(value: object): value is MeetingPointRequest {
    return true;
}

export function MeetingPointRequestFromJSON(json: any): MeetingPointRequest {
    return MeetingPointRequestFromJSONTyped(json, false);
}

export function MeetingPointRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeetingPointRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'listingId': json['listingId'] == null ? undefined : json['listingId'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
    };
}

export function MeetingPointRequestToJSON(json: any): MeetingPointRequest {
    return MeetingPointRequestToJSONTyped(json, false);
}

export function MeetingPointRequestToJSONTyped(value?: MeetingPointRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listingId': value['listingId'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

