/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PickupConfirmRequest
 */
export interface PickupConfirmRequest {
    /**
     * 
     * @type {number}
     * @memberof PickupConfirmRequest
     */
    listingId?: number;
}

/**
 * Check if a given object implements the PickupConfirmRequest interface.
 */
export function instanceOfPickupConfirmRequest(value: object): value is PickupConfirmRequest {
    return true;
}

export function PickupConfirmRequestFromJSON(json: any): PickupConfirmRequest {
    return PickupConfirmRequestFromJSONTyped(json, false);
}

export function PickupConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupConfirmRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'listingId': json['listingId'] == null ? undefined : json['listingId'],
    };
}

export function PickupConfirmRequestToJSON(json: any): PickupConfirmRequest {
    return PickupConfirmRequestToJSONTyped(json, false);
}

export function PickupConfirmRequestToJSONTyped(value?: PickupConfirmRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listingId': value['listingId'],
    };
}

