/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PickupRequest
 */
export interface PickupRequest {
    /**
     * 
     * @type {number}
     * @memberof PickupRequest
     */
    listingId?: number;
}

/**
 * Check if a given object implements the PickupRequest interface.
 */
export function instanceOfPickupRequest(value: object): value is PickupRequest {
    return true;
}

export function PickupRequestFromJSON(json: any): PickupRequest {
    return PickupRequestFromJSONTyped(json, false);
}

export function PickupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'listingId': json['listingId'] == null ? undefined : json['listingId'],
    };
}

export function PickupRequestToJSON(json: any): PickupRequest {
    return PickupRequestToJSONTyped(json, false);
}

export function PickupRequestToJSONTyped(value?: PickupRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listingId': value['listingId'],
    };
}

