/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiptSubmitRequest
 */
export interface ReceiptSubmitRequest {
    /**
     * 
     * @type {number}
     * @memberof ReceiptSubmitRequest
     */
    listingId?: number;
    /**
     * 
     * @type {string}
     * @memberof ReceiptSubmitRequest
     */
    receiptImageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ReceiptSubmitRequest
     */
    reportedAmount?: number;
}

/**
 * Check if a given object implements the ReceiptSubmitRequest interface.
 */
export function instanceOfReceiptSubmitRequest(value: object): value is ReceiptSubmitRequest {
    return true;
}

export function ReceiptSubmitRequestFromJSON(json: any): ReceiptSubmitRequest {
    return ReceiptSubmitRequestFromJSONTyped(json, false);
}

export function ReceiptSubmitRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptSubmitRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'listingId': json['listingId'] == null ? undefined : json['listingId'],
        'receiptImageUrl': json['receiptImageUrl'] == null ? undefined : json['receiptImageUrl'],
        'reportedAmount': json['reportedAmount'] == null ? undefined : json['reportedAmount'],
    };
}

export function ReceiptSubmitRequestToJSON(json: any): ReceiptSubmitRequest {
    return ReceiptSubmitRequestToJSONTyped(json, false);
}

export function ReceiptSubmitRequestToJSONTyped(value?: ReceiptSubmitRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listingId': value['listingId'],
        'receiptImageUrl': value['receiptImageUrl'],
        'reportedAmount': value['reportedAmount'],
    };
}

