/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiptVerifyRequest
 */
export interface ReceiptVerifyRequest {
    /**
     * 
     * @type {number}
     * @memberof ReceiptVerifyRequest
     */
    listingId?: number;
    /**
     * 
     * @type {number}
     * @memberof ReceiptVerifyRequest
     */
    verifiedAmount?: number;
}

/**
 * Check if a given object implements the ReceiptVerifyRequest interface.
 */
export function instanceOfReceiptVerifyRequest(value: object): value is ReceiptVerifyRequest {
    return true;
}

export function ReceiptVerifyRequestFromJSON(json: any): ReceiptVerifyRequest {
    return ReceiptVerifyRequestFromJSONTyped(json, false);
}

export function ReceiptVerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiptVerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'listingId': json['listingId'] == null ? undefined : json['listingId'],
        'verifiedAmount': json['verifiedAmount'] == null ? undefined : json['verifiedAmount'],
    };
}

export function ReceiptVerifyRequestToJSON(json: any): ReceiptVerifyRequest {
    return ReceiptVerifyRequestToJSONTyped(json, false);
}

export function ReceiptVerifyRequestToJSONTyped(value?: ReceiptVerifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listingId': value['listingId'],
        'verifiedAmount': value['verifiedAmount'],
    };
}

