/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecycleMaterialType } from './RecycleMaterialType';
import {
    RecycleMaterialTypeFromJSON,
    RecycleMaterialTypeFromJSONTyped,
    RecycleMaterialTypeToJSON,
    RecycleMaterialTypeToJSONTyped,
} from './RecycleMaterialType';

/**
 * 
 * @export
 * @interface RecyclerMaterialBreakdown
 */
export interface RecyclerMaterialBreakdown {
    /**
     * 
     * @type {RecycleMaterialType}
     * @memberof RecyclerMaterialBreakdown
     */
    material?: RecycleMaterialType;
    /**
     * 
     * @type {number}
     * @memberof RecyclerMaterialBreakdown
     */
    quantity?: number;
}



/**
 * Check if a given object implements the RecyclerMaterialBreakdown interface.
 */
export function instanceOfRecyclerMaterialBreakdown(value: object): value is RecyclerMaterialBreakdown {
    return true;
}

export function RecyclerMaterialBreakdownFromJSON(json: any): RecyclerMaterialBreakdown {
    return RecyclerMaterialBreakdownFromJSONTyped(json, false);
}

export function RecyclerMaterialBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecyclerMaterialBreakdown {
    if (json == null) {
        return json;
    }
    return {
        
        'material': json['material'] == null ? undefined : RecycleMaterialTypeFromJSON(json['material']),
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
    };
}

export function RecyclerMaterialBreakdownToJSON(json: any): RecyclerMaterialBreakdown {
    return RecyclerMaterialBreakdownToJSONTyped(json, false);
}

export function RecyclerMaterialBreakdownToJSONTyped(value?: RecyclerMaterialBreakdown | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'material': RecycleMaterialTypeToJSON(value['material']),
        'quantity': value['quantity'],
    };
}

