/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecycleListingImageResponse
 */
export interface RecycleListingImageResponse {
    /**
     * 
     * @type {number}
     * @memberof RecycleListingImageResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RecycleListingImageResponse
     */
    fileName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecycleListingImageResponse
     */
    contentType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecycleListingImageResponse
     */
    order?: number;
}

/**
 * Check if a given object implements the RecycleListingImageResponse interface.
 */
export function instanceOfRecycleListingImageResponse(value: object): value is RecycleListingImageResponse {
    return true;
}

export function RecycleListingImageResponseFromJSON(json: any): RecycleListingImageResponse {
    return RecycleListingImageResponseFromJSONTyped(json, false);
}

export function RecycleListingImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecycleListingImageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'order': json['order'] == null ? undefined : json['order'],
    };
}

export function RecycleListingImageResponseToJSON(json: any): RecycleListingImageResponse {
    return RecycleListingImageResponseToJSONTyped(json, false);
}

export function RecycleListingImageResponseToJSONTyped(value?: RecycleListingImageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'fileName': value['fileName'],
        'contentType': value['contentType'],
        'order': value['order'],
    };
}

