/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecycleListingImageResponse } from './RecycleListingImageResponse';
import {
    RecycleListingImageResponseFromJSON,
    RecycleListingImageResponseFromJSONTyped,
    RecycleListingImageResponseToJSON,
    RecycleListingImageResponseToJSONTyped,
} from './RecycleListingImageResponse';
import type { ListingStatus } from './ListingStatus';
import {
    ListingStatusFromJSON,
    ListingStatusFromJSONTyped,
    ListingStatusToJSON,
    ListingStatusToJSONTyped,
} from './ListingStatus';
import type { RecycleListingItemResponse } from './RecycleListingItemResponse';
import {
    RecycleListingItemResponseFromJSON,
    RecycleListingItemResponseFromJSONTyped,
    RecycleListingItemResponseToJSON,
    RecycleListingItemResponseToJSONTyped,
} from './RecycleListingItemResponse';

/**
 * 
 * @export
 * @interface RecycleListingResponse
 */
export interface RecycleListingResponse {
    /**
     * 
     * @type {number}
     * @memberof RecycleListingResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RecycleListingResponse
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecycleListingResponse
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecycleListingResponse
     */
    estimatedValue?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof RecycleListingResponse
     */
    availableFrom?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RecycleListingResponse
     */
    availableTo?: Date;
    /**
     * 
     * @type {string}
     * @memberof RecycleListingResponse
     */
    createdByUserId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RecycleListingResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof RecycleListingResponse
     */
    isActive?: boolean;
    /**
     * 
     * @type {ListingStatus}
     * @memberof RecycleListingResponse
     */
    status?: ListingStatus;
    /**
     * 
     * @type {string}
     * @memberof RecycleListingResponse
     */
    cityExternalId?: string;
    /**
     * 
     * @type {string}
     * @memberof RecycleListingResponse
     */
    assignedRecyclerUserId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecycleListingResponse
     */
    chatSessionId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecycleListingResponse
     */
    reportedAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RecycleListingResponse
     */
    verifiedAmount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RecycleListingResponse
     */
    receiptImageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecycleListingResponse
     */
    meetingPointLatitude?: number | null;
    /**
     * 
     * @type {number}
     * @memberof RecycleListingResponse
     */
    meetingPointLongtitude?: number | null;
    /**
     * 
     * @type {Array<RecycleListingItemResponse>}
     * @memberof RecycleListingResponse
     */
    items?: Array<RecycleListingItemResponse> | null;
    /**
     * 
     * @type {Array<RecycleListingImageResponse>}
     * @memberof RecycleListingResponse
     */
    images?: Array<RecycleListingImageResponse> | null;
}



/**
 * Check if a given object implements the RecycleListingResponse interface.
 */
export function instanceOfRecycleListingResponse(value: object): value is RecycleListingResponse {
    return true;
}

export function RecycleListingResponseFromJSON(json: any): RecycleListingResponse {
    return RecycleListingResponseFromJSONTyped(json, false);
}

export function RecycleListingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecycleListingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'estimatedValue': json['estimatedValue'] == null ? undefined : json['estimatedValue'],
        'availableFrom': json['availableFrom'] == null ? undefined : (new Date(json['availableFrom'])),
        'availableTo': json['availableTo'] == null ? undefined : (new Date(json['availableTo'])),
        'createdByUserId': json['createdByUserId'] == null ? undefined : json['createdByUserId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'isActive': json['isActive'] == null ? undefined : json['isActive'],
        'status': json['status'] == null ? undefined : ListingStatusFromJSON(json['status']),
        'cityExternalId': json['cityExternalId'] == null ? undefined : json['cityExternalId'],
        'assignedRecyclerUserId': json['assignedRecyclerUserId'] == null ? undefined : json['assignedRecyclerUserId'],
        'chatSessionId': json['chatSessionId'] == null ? undefined : json['chatSessionId'],
        'reportedAmount': json['reportedAmount'] == null ? undefined : json['reportedAmount'],
        'verifiedAmount': json['verifiedAmount'] == null ? undefined : json['verifiedAmount'],
        'receiptImageUrl': json['receiptImageUrl'] == null ? undefined : json['receiptImageUrl'],
        'meetingPointLatitude': json['meetingPointLatitude'] == null ? undefined : json['meetingPointLatitude'],
        'meetingPointLongtitude': json['meetingPointLongtitude'] == null ? undefined : json['meetingPointLongtitude'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(RecycleListingItemResponseFromJSON)),
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(RecycleListingImageResponseFromJSON)),
    };
}

export function RecycleListingResponseToJSON(json: any): RecycleListingResponse {
    return RecycleListingResponseToJSONTyped(json, false);
}

export function RecycleListingResponseToJSONTyped(value?: RecycleListingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'estimatedValue': value['estimatedValue'],
        'availableFrom': value['availableFrom'] == null ? undefined : ((value['availableFrom']).toISOString().substring(0,10)),
        'availableTo': value['availableTo'] == null ? undefined : ((value['availableTo']).toISOString().substring(0,10)),
        'createdByUserId': value['createdByUserId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'isActive': value['isActive'],
        'status': ListingStatusToJSON(value['status']),
        'cityExternalId': value['cityExternalId'],
        'assignedRecyclerUserId': value['assignedRecyclerUserId'],
        'chatSessionId': value['chatSessionId'],
        'reportedAmount': value['reportedAmount'],
        'verifiedAmount': value['verifiedAmount'],
        'receiptImageUrl': value['receiptImageUrl'],
        'meetingPointLatitude': value['meetingPointLatitude'],
        'meetingPointLongtitude': value['meetingPointLongtitude'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(RecycleListingItemResponseToJSON)),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(RecycleListingImageResponseToJSON)),
    };
}

