/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecycleListingResponse } from './RecycleListingResponse';
import {
    RecycleListingResponseFromJSON,
    RecycleListingResponseFromJSONTyped,
    RecycleListingResponseToJSON,
    RecycleListingResponseToJSONTyped,
} from './RecycleListingResponse';

/**
 * 
 * @export
 * @interface RecycleListingResponsePagedResult
 */
export interface RecycleListingResponsePagedResult {
    /**
     * 
     * @type {Array<RecycleListingResponse>}
     * @memberof RecycleListingResponsePagedResult
     */
    items?: Array<RecycleListingResponse> | null;
    /**
     * 
     * @type {number}
     * @memberof RecycleListingResponsePagedResult
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof RecycleListingResponsePagedResult
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof RecycleListingResponsePagedResult
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof RecycleListingResponsePagedResult
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof RecycleListingResponsePagedResult
     */
    readonly hasPrevious?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof RecycleListingResponsePagedResult
     */
    readonly hasNext?: boolean;
}

/**
 * Check if a given object implements the RecycleListingResponsePagedResult interface.
 */
export function instanceOfRecycleListingResponsePagedResult(value: object): value is RecycleListingResponsePagedResult {
    return true;
}

export function RecycleListingResponsePagedResultFromJSON(json: any): RecycleListingResponsePagedResult {
    return RecycleListingResponsePagedResultFromJSONTyped(json, false);
}

export function RecycleListingResponsePagedResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecycleListingResponsePagedResult {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(RecycleListingResponseFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'hasPrevious': json['hasPrevious'] == null ? undefined : json['hasPrevious'],
        'hasNext': json['hasNext'] == null ? undefined : json['hasNext'],
    };
}

export function RecycleListingResponsePagedResultToJSON(json: any): RecycleListingResponsePagedResult {
    return RecycleListingResponsePagedResultToJSONTyped(json, false);
}

export function RecycleListingResponsePagedResultToJSONTyped(value?: Omit<RecycleListingResponsePagedResult, 'totalPages'|'hasPrevious'|'hasNext'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(RecycleListingResponseToJSON)),
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
    };
}

