/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecycleListing } from './RecycleListing';
import {
    RecycleListingFromJSON,
    RecycleListingFromJSONTyped,
    RecycleListingToJSON,
    RecycleListingToJSONTyped,
} from './RecycleListing';

/**
 * 
 * @export
 * @interface RecycleListingApplicant
 */
export interface RecycleListingApplicant {
    /**
     * 
     * @type {number}
     * @memberof RecycleListingApplicant
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof RecycleListingApplicant
     */
    listingId?: number;
    /**
     * 
     * @type {string}
     * @memberof RecycleListingApplicant
     */
    recyclerUserId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RecycleListingApplicant
     */
    appliedAt?: Date;
    /**
     * 
     * @type {RecycleListing}
     * @memberof RecycleListingApplicant
     */
    listing?: RecycleListing;
}

/**
 * Check if a given object implements the RecycleListingApplicant interface.
 */
export function instanceOfRecycleListingApplicant(value: object): value is RecycleListingApplicant {
    return true;
}

export function RecycleListingApplicantFromJSON(json: any): RecycleListingApplicant {
    return RecycleListingApplicantFromJSONTyped(json, false);
}

export function RecycleListingApplicantFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecycleListingApplicant {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'listingId': json['listingId'] == null ? undefined : json['listingId'],
        'recyclerUserId': json['recyclerUserId'] == null ? undefined : json['recyclerUserId'],
        'appliedAt': json['appliedAt'] == null ? undefined : (new Date(json['appliedAt'])),
        'listing': json['listing'] == null ? undefined : RecycleListingFromJSON(json['listing']),
    };
}

export function RecycleListingApplicantToJSON(json: any): RecycleListingApplicant {
    return RecycleListingApplicantToJSONTyped(json, false);
}

export function RecycleListingApplicantToJSONTyped(value?: RecycleListingApplicant | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'listingId': value['listingId'],
        'recyclerUserId': value['recyclerUserId'],
        'appliedAt': value['appliedAt'] == null ? undefined : ((value['appliedAt']).toISOString()),
        'listing': RecycleListingToJSON(value['listing']),
    };
}

