/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecyclerMaterialBreakdown } from './RecyclerMaterialBreakdown';
import {
    RecyclerMaterialBreakdownFromJSON,
    RecyclerMaterialBreakdownFromJSONTyped,
    RecyclerMaterialBreakdownToJSON,
    RecyclerMaterialBreakdownToJSONTyped,
} from './RecyclerMaterialBreakdown';

/**
 * 
 * @export
 * @interface RecyclerStatisticsResult
 */
export interface RecyclerStatisticsResult {
    /**
     * 
     * @type {number}
     * @memberof RecyclerStatisticsResult
     */
    listingCount?: number;
    /**
     * 
     * @type {number}
     * @memberof RecyclerStatisticsResult
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof RecyclerStatisticsResult
     */
    totalApproximateWorth?: number;
    /**
     * 
     * @type {number}
     * @memberof RecyclerStatisticsResult
     */
    totalReportedAmount?: number;
    /**
     * 
     * @type {Array<RecyclerMaterialBreakdown>}
     * @memberof RecyclerStatisticsResult
     */
    breakdown?: Array<RecyclerMaterialBreakdown> | null;
}

/**
 * Check if a given object implements the RecyclerStatisticsResult interface.
 */
export function instanceOfRecyclerStatisticsResult(value: object): value is RecyclerStatisticsResult {
    return true;
}

export function RecyclerStatisticsResultFromJSON(json: any): RecyclerStatisticsResult {
    return RecyclerStatisticsResultFromJSONTyped(json, false);
}

export function RecyclerStatisticsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecyclerStatisticsResult {
    if (json == null) {
        return json;
    }
    return {
        
        'listingCount': json['listingCount'] == null ? undefined : json['listingCount'],
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'totalApproximateWorth': json['totalApproximateWorth'] == null ? undefined : json['totalApproximateWorth'],
        'totalReportedAmount': json['totalReportedAmount'] == null ? undefined : json['totalReportedAmount'],
        'breakdown': json['breakdown'] == null ? undefined : ((json['breakdown'] as Array<any>).map(RecyclerMaterialBreakdownFromJSON)),
    };
}

export function RecyclerStatisticsResultToJSON(json: any): RecyclerStatisticsResult {
    return RecyclerStatisticsResultToJSONTyped(json, false);
}

export function RecyclerStatisticsResultToJSONTyped(value?: RecyclerStatisticsResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'listingCount': value['listingCount'],
        'totalItems': value['totalItems'],
        'totalApproximateWorth': value['totalApproximateWorth'],
        'totalReportedAmount': value['totalReportedAmount'],
        'breakdown': value['breakdown'] == null ? undefined : ((value['breakdown'] as Array<any>).map(RecyclerMaterialBreakdownToJSON)),
    };
}

