/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscribeRequest
 */
export interface SubscribeRequest {
    /**
     * 
     * @type {string}
     * @memberof SubscribeRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SubscribeRequest
     */
    email?: string | null;
}

/**
 * Check if a given object implements the SubscribeRequest interface.
 */
export function instanceOfSubscribeRequest(value: object): value is SubscribeRequest {
    return true;
}

export function SubscribeRequestFromJSON(json: any): SubscribeRequest {
    return SubscribeRequestFromJSONTyped(json, false);
}

export function SubscribeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscribeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function SubscribeRequestToJSON(json: any): SubscribeRequest {
    return SubscribeRequestToJSONTyped(json, false);
}

export function SubscribeRequestToJSONTyped(value?: SubscribeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
    };
}

