/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscribeResponse
 */
export interface SubscribeResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SubscribeResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SubscribeResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the SubscribeResponse interface.
 */
export function instanceOfSubscribeResponse(value: object): value is SubscribeResponse {
    return true;
}

export function SubscribeResponseFromJSON(json: any): SubscribeResponse {
    return SubscribeResponseFromJSONTyped(json, false);
}

export function SubscribeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscribeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function SubscribeResponseToJSON(json: any): SubscribeResponse {
    return SubscribeResponseToJSONTyped(json, false);
}

export function SubscribeResponseToJSONTyped(value?: SubscribeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
    };
}

