/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnsubscribeRequest
 */
export interface UnsubscribeRequest {
    /**
     * 
     * @type {string}
     * @memberof UnsubscribeRequest
     */
    email?: string | null;
}

/**
 * Check if a given object implements the UnsubscribeRequest interface.
 */
export function instanceOfUnsubscribeRequest(value: object): value is UnsubscribeRequest {
    return true;
}

export function UnsubscribeRequestFromJSON(json: any): UnsubscribeRequest {
    return UnsubscribeRequestFromJSONTyped(json, false);
}

export function UnsubscribeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnsubscribeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function UnsubscribeRequestToJSON(json: any): UnsubscribeRequest {
    return UnsubscribeRequestToJSONTyped(json, false);
}

export function UnsubscribeRequestToJSONTyped(value?: UnsubscribeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

