/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnsubscribeResponse
 */
export interface UnsubscribeResponse {
    /**
     * 
     * @type {boolean}
     * @memberof UnsubscribeResponse
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UnsubscribeResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the UnsubscribeResponse interface.
 */
export function instanceOfUnsubscribeResponse(value: object): value is UnsubscribeResponse {
    return true;
}

export function UnsubscribeResponseFromJSON(json: any): UnsubscribeResponse {
    return UnsubscribeResponseFromJSONTyped(json, false);
}

export function UnsubscribeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnsubscribeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function UnsubscribeResponseToJSON(json: any): UnsubscribeResponse {
    return UnsubscribeResponseToJSONTyped(json, false);
}

export function UnsubscribeResponseToJSONTyped(value?: UnsubscribeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'error': value['error'],
    };
}

