/* tslint:disable */
/* eslint-disable */
/**
 * PantmigService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SubscribeRequest,
  SubscribeResponse,
  UnsubscribeRequest,
  UnsubscribeResponse,
} from '../models/index';
import {
    SubscribeRequestFromJSON,
    SubscribeRequestToJSON,
    SubscribeResponseFromJSON,
    SubscribeResponseToJSON,
    UnsubscribeRequestFromJSON,
    UnsubscribeRequestToJSON,
    UnsubscribeResponseFromJSON,
    UnsubscribeResponseToJSON,
} from '../models/index';

export interface NewsletterSubscribeRequest {
    subscribeRequest: SubscribeRequest;
}

export interface NewsletterUnsubscribeRequest {
    unsubscribeRequest: UnsubscribeRequest;
}

export interface NewsletterUnsubscribeGetRequest {
    email: string;
}

/**
 * 
 */
export class NewsletterApi extends runtime.BaseAPI {

    /**
     * Stores the subscriber in the database and sends a confirmation email.
     * Subscribe to the newsletter
     */
    async newsletterSubscribeRaw(requestParameters: NewsletterSubscribeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscribeResponse>> {
        if (requestParameters['subscribeRequest'] == null) {
            throw new runtime.RequiredError(
                'subscribeRequest',
                'Required parameter "subscribeRequest" was null or undefined when calling newsletterSubscribe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/newsletter/subscribe`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubscribeRequestToJSON(requestParameters['subscribeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscribeResponseFromJSON(jsonValue));
    }

    /**
     * Stores the subscriber in the database and sends a confirmation email.
     * Subscribe to the newsletter
     */
    async newsletterSubscribe(requestParameters: NewsletterSubscribeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscribeResponse> {
        const response = await this.newsletterSubscribeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the email from the newsletter subscriber list. Idempotent.
     * Unsubscribe from the newsletter
     */
    async newsletterUnsubscribeRaw(requestParameters: NewsletterUnsubscribeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UnsubscribeResponse>> {
        if (requestParameters['unsubscribeRequest'] == null) {
            throw new runtime.RequiredError(
                'unsubscribeRequest',
                'Required parameter "unsubscribeRequest" was null or undefined when calling newsletterUnsubscribe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/newsletter/unsubscribe`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UnsubscribeRequestToJSON(requestParameters['unsubscribeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UnsubscribeResponseFromJSON(jsonValue));
    }

    /**
     * Removes the email from the newsletter subscriber list. Idempotent.
     * Unsubscribe from the newsletter
     */
    async newsletterUnsubscribe(requestParameters: NewsletterUnsubscribeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UnsubscribeResponse> {
        const response = await this.newsletterUnsubscribeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the email using a simple GET. Intended for List-Unsubscribe one-click.
     * One-click unsubscribe
     */
    async newsletterUnsubscribeGetRaw(requestParameters: NewsletterUnsubscribeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling newsletterUnsubscribeGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/newsletter/unsubscribe`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the email using a simple GET. Intended for List-Unsubscribe one-click.
     * One-click unsubscribe
     */
    async newsletterUnsubscribeGet(requestParameters: NewsletterUnsubscribeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.newsletterUnsubscribeGetRaw(requestParameters, initOverrides);
    }

}
