/* tslint:disable */
/* eslint-disable */
/**
 * AuthService API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthResponse,
  AvailabilityResult,
  ChangeEmailRequest,
  ChangeEmailResult,
  ChangePasswordRequest,
  ChangePasswordResult,
  DisableAccountRequest,
  LoginRequest,
  LoginResult,
  OperationResult,
  RegisterRequest,
  RegisterResult,
  TokenRefreshRequest,
  UserInformationDTO,
  UserInformationResult,
  UsersLookupRequest,
  UsersLookupResult,
} from '../models/index';
import {
    AuthResponseFromJSON,
    AuthResponseToJSON,
    AvailabilityResultFromJSON,
    AvailabilityResultToJSON,
    ChangeEmailRequestFromJSON,
    ChangeEmailRequestToJSON,
    ChangeEmailResultFromJSON,
    ChangeEmailResultToJSON,
    ChangePasswordRequestFromJSON,
    ChangePasswordRequestToJSON,
    ChangePasswordResultFromJSON,
    ChangePasswordResultToJSON,
    DisableAccountRequestFromJSON,
    DisableAccountRequestToJSON,
    LoginRequestFromJSON,
    LoginRequestToJSON,
    LoginResultFromJSON,
    LoginResultToJSON,
    OperationResultFromJSON,
    OperationResultToJSON,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
    RegisterResultFromJSON,
    RegisterResultToJSON,
    TokenRefreshRequestFromJSON,
    TokenRefreshRequestToJSON,
    UserInformationDTOFromJSON,
    UserInformationDTOToJSON,
    UserInformationResultFromJSON,
    UserInformationResultToJSON,
    UsersLookupRequestFromJSON,
    UsersLookupRequestToJSON,
    UsersLookupResultFromJSON,
    UsersLookupResultToJSON,
} from '../models/index';

export interface AuthChangeEmailRequest {
    changeEmailRequest: ChangeEmailRequest;
}

export interface AuthChangePasswordRequest {
    changePasswordRequest: ChangePasswordRequest;
}

export interface AuthCheckEmailRequest {
    email: string;
}

export interface AuthCheckPhoneRequest {
    phone: string;
}

export interface AuthConfirmEmailRequest {
    userId: string;
    token: string;
}

export interface AuthConfirmEmailChangeRequest {
    userId: string;
    email: string;
    token: string;
}

export interface AuthDisableAccountRequest {
    disableAccountRequest: DisableAccountRequest;
}

export interface AuthGetUserByIdRequest {
    id: string;
}

export interface AuthLoginRequest {
    loginRequest: LoginRequest;
}

export interface AuthRefreshRequest {
    tokenRefreshRequest: TokenRefreshRequest;
}

export interface AuthRegisterRequest {
    registerRequest: RegisterRequest;
}

export interface AuthUsersLookupRequest {
    usersLookupRequest: UsersLookupRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Initiates email change by sending a confirmation link to the new address.
     * Request email change
     */
    async authChangeEmailRaw(requestParameters: AuthChangeEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChangeEmailResult>> {
        if (requestParameters['changeEmailRequest'] == null) {
            throw new runtime.RequiredError(
                'changeEmailRequest',
                'Required parameter "changeEmailRequest" was null or undefined when calling authChangeEmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/change-email`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangeEmailRequestToJSON(requestParameters['changeEmailRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChangeEmailResultFromJSON(jsonValue));
    }

    /**
     * Initiates email change by sending a confirmation link to the new address.
     * Request email change
     */
    async authChangeEmail(requestParameters: AuthChangeEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChangeEmailResult> {
        const response = await this.authChangeEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Changes the authenticated user\'s password and rotates tokens.
     * Change password
     */
    async authChangePasswordRaw(requestParameters: AuthChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChangePasswordResult>> {
        if (requestParameters['changePasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'changePasswordRequest',
                'Required parameter "changePasswordRequest" was null or undefined when calling authChangePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/change-password`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChangePasswordRequestToJSON(requestParameters['changePasswordRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChangePasswordResultFromJSON(jsonValue));
    }

    /**
     * Changes the authenticated user\'s password and rotates tokens.
     * Change password
     */
    async authChangePassword(requestParameters: AuthChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChangePasswordResult> {
        const response = await this.authChangePasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns whether a user with the provided email already exists.
     * Check if email is already taken
     */
    async authCheckEmailRaw(requestParameters: AuthCheckEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AvailabilityResult>> {
        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling authCheckEmail().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/check-email`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AvailabilityResultFromJSON(jsonValue));
    }

    /**
     * Returns whether a user with the provided email already exists.
     * Check if email is already taken
     */
    async authCheckEmail(requestParameters: AuthCheckEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AvailabilityResult> {
        const response = await this.authCheckEmailRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns whether a user with the provided phone number already exists.
     * Check if phone number is already taken
     */
    async authCheckPhoneRaw(requestParameters: AuthCheckPhoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AvailabilityResult>> {
        if (requestParameters['phone'] == null) {
            throw new runtime.RequiredError(
                'phone',
                'Required parameter "phone" was null or undefined when calling authCheckPhone().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['phone'] != null) {
            queryParameters['phone'] = requestParameters['phone'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/check-phone`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AvailabilityResultFromJSON(jsonValue));
    }

    /**
     * Returns whether a user with the provided phone number already exists.
     * Check if phone number is already taken
     */
    async authCheckPhone(requestParameters: AuthCheckPhoneRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AvailabilityResult> {
        const response = await this.authCheckPhoneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verifies the email confirmation token and marks the user\'s email as confirmed.
     * Confirm user email
     */
    async authConfirmEmailRaw(requestParameters: AuthConfirmEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling authConfirmEmail().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling authConfirmEmail().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/confirm-email`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Verifies the email confirmation token and marks the user\'s email as confirmed.
     * Confirm user email
     */
    async authConfirmEmail(requestParameters: AuthConfirmEmailRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authConfirmEmailRaw(requestParameters, initOverrides);
    }

    /**
     * Finalizes email change using token sent to new address.
     * Confirm email change
     */
    async authConfirmEmailChangeRaw(requestParameters: AuthConfirmEmailChangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling authConfirmEmailChange().'
            );
        }

        if (requestParameters['email'] == null) {
            throw new runtime.RequiredError(
                'email',
                'Required parameter "email" was null or undefined when calling authConfirmEmailChange().'
            );
        }

        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling authConfirmEmailChange().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['token'] != null) {
            queryParameters['token'] = requestParameters['token'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/confirm-email-change`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Finalizes email change using token sent to new address.
     * Confirm email change
     */
    async authConfirmEmailChange(requestParameters: AuthConfirmEmailChangeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authConfirmEmailChangeRaw(requestParameters, initOverrides);
    }

    /**
     * Marks the authenticated user\'s account as disabled and revokes active tokens.
     * Disable account
     */
    async authDisableAccountRaw(requestParameters: AuthDisableAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OperationResult>> {
        if (requestParameters['disableAccountRequest'] == null) {
            throw new runtime.RequiredError(
                'disableAccountRequest',
                'Required parameter "disableAccountRequest" was null or undefined when calling authDisableAccount().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/disable-account`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DisableAccountRequestToJSON(requestParameters['disableAccountRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OperationResultFromJSON(jsonValue));
    }

    /**
     * Marks the authenticated user\'s account as disabled and revokes active tokens.
     * Disable account
     */
    async authDisableAccount(requestParameters: AuthDisableAccountRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OperationResult> {
        const response = await this.authDisableAccountRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns public profile information for a user, including rating.
     * Get user info by id
     */
    async authGetUserByIdRaw(requestParameters: AuthGetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserInformationResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling authGetUserById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/users/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserInformationResultFromJSON(jsonValue));
    }

    /**
     * Returns public profile information for a user, including rating.
     * Get user info by id
     */
    async authGetUserById(requestParameters: AuthGetUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInformationResult> {
        const response = await this.authGetUserByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Authenticates a user with either email or username and returns access and refresh tokens.
     * Login with email/username and password
     */
    async authLoginRaw(requestParameters: AuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LoginResult>> {
        if (requestParameters['loginRequest'] == null) {
            throw new runtime.RequiredError(
                'loginRequest',
                'Required parameter "loginRequest" was null or undefined when calling authLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/login`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginRequestToJSON(requestParameters['loginRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LoginResultFromJSON(jsonValue));
    }

    /**
     * Authenticates a user with either email or username and returns access and refresh tokens.
     * Login with email/username and password
     */
    async authLogin(requestParameters: AuthLoginRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LoginResult> {
        const response = await this.authLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns basic profile information for the authenticated user.
     * Get current user info
     */
    async authMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserInformationDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/me`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserInformationDTOFromJSON(jsonValue));
    }

    /**
     * Returns basic profile information for the authenticated user.
     * Get current user info
     */
    async authMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInformationDTO> {
        const response = await this.authMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Rotates the refresh token and issues a new access token.
     * Refresh access token
     */
    async authRefreshRaw(requestParameters: AuthRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthResponse>> {
        if (requestParameters['tokenRefreshRequest'] == null) {
            throw new runtime.RequiredError(
                'tokenRefreshRequest',
                'Required parameter "tokenRefreshRequest" was null or undefined when calling authRefresh().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/refresh`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRefreshRequestToJSON(requestParameters['tokenRefreshRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthResponseFromJSON(jsonValue));
    }

    /**
     * Rotates the refresh token and issues a new access token.
     * Refresh access token
     */
    async authRefresh(requestParameters: AuthRefreshRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthResponse> {
        const response = await this.authRefreshRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a new user account and returns access and refresh tokens.
     * Register a new user
     */
    async authRegisterRaw(requestParameters: AuthRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterResult>> {
        if (requestParameters['registerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerRequest',
                'Required parameter "registerRequest" was null or undefined when calling authRegister().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/register`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterResultFromJSON(jsonValue));
    }

    /**
     * Creates a new user account and returns access and refresh tokens.
     * Register a new user
     */
    async authRegister(requestParameters: AuthRegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterResult> {
        const response = await this.authRegisterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns ratings for a list of user ids to reduce round-trips. Uses in-memory cache for faster responses.
     * Batch lookup users\' ratings
     */
    async authUsersLookupRaw(requestParameters: AuthUsersLookupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UsersLookupResult>> {
        if (requestParameters['usersLookupRequest'] == null) {
            throw new runtime.RequiredError(
                'usersLookupRequest',
                'Required parameter "usersLookupRequest" was null or undefined when calling authUsersLookup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // Bearer authentication
        }


        let urlPath = `/auth/users/lookup`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UsersLookupRequestToJSON(requestParameters['usersLookupRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UsersLookupResultFromJSON(jsonValue));
    }

    /**
     * Returns ratings for a list of user ids to reduce round-trips. Uses in-memory cache for faster responses.
     * Batch lookup users\' ratings
     */
    async authUsersLookup(requestParameters: AuthUsersLookupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UsersLookupResult> {
        const response = await this.authUsersLookupRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
